-- ============================================================================
-- SafePath BD - Smart Road Safety & Safe Route Recommendation System
-- Full MySQL Database Schema
-- Target: MySQL 8.x / MySQL Workbench
-- Database: safepath_bd
--
-- IMPORTANT:
--   1) This script DROPS the existing database named `safepath_bd`.
--   2) Run the whole file in MySQL Workbench in one execution.
--   3) Passwords must be stored as secure hashes generated by ASP.NET Identity/
--      your authentication layer. Never store plain-text passwords.
-- ============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP DATABASE IF EXISTS safepath_bd;
CREATE DATABASE safepath_bd
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;
USE safepath_bd;

SET FOREIGN_KEY_CHECKS = 1;

-- ============================================================================
-- 1. USER, ROLE & ACCESS MANAGEMENT
-- ============================================================================

CREATE TABLE users (
    user_id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    full_name            VARCHAR(150) NOT NULL,
    email                VARCHAR(190) NOT NULL,
    phone                VARCHAR(30) NULL,
    password_hash        VARCHAR(255) NOT NULL,
    profile_image_url    VARCHAR(1000) NULL,
    is_active            BOOLEAN NOT NULL DEFAULT TRUE,
    email_verified       BOOLEAN NOT NULL DEFAULT FALSE,
    last_login_at        DATETIME NULL,
    created_at           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id),
    UNIQUE KEY uq_users_email (email),
    UNIQUE KEY uq_users_phone (phone)
) ENGINE=InnoDB COMMENT='Registered SafePath BD users.';

CREATE TABLE roles (
    role_id              SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    role_name            VARCHAR(50) NOT NULL,
    description          VARCHAR(255) NULL,
    created_at           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (role_id),
    UNIQUE KEY uq_roles_name (role_name)
) ENGINE=InnoDB COMMENT='Application roles such as Admin, Moderator and User.';

CREATE TABLE user_roles (
    user_role_id         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id              BIGINT UNSIGNED NOT NULL,
    role_id              SMALLINT UNSIGNED NOT NULL,
    assigned_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_role_id),
    UNIQUE KEY uq_user_roles_user_role (user_id, role_id),
    KEY ix_user_roles_role (role_id),
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES users(user_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id) REFERENCES roles(role_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB COMMENT='Many-to-many bridge between users and roles.';

-- ============================================================================
-- 2. LOCATION, ROAD & ROAD SEGMENT MANAGEMENT
-- ============================================================================

CREATE TABLE locations (
    location_id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    latitude             DECIMAL(10,7) NOT NULL,
    longitude            DECIMAL(10,7) NOT NULL,
    address_line         VARCHAR(500) NULL,
    landmark_name        VARCHAR(200) NULL,
    area_name            VARCHAR(150) NULL,
    city                 VARCHAR(100) NULL,
    district             VARCHAR(100) NULL,
    division_name        VARCHAR(100) NULL,
    country              VARCHAR(100) NOT NULL DEFAULT 'Bangladesh',
    place_provider       ENUM('GOOGLE','OSM','MANUAL','OTHER') NOT NULL DEFAULT 'MANUAL',
    external_place_id    VARCHAR(255) NULL,
    created_at           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (location_id),
    KEY ix_locations_lat_lng (latitude, longitude),
    KEY ix_locations_city_area (city, area_name),
    KEY ix_locations_external_place (place_provider, external_place_id),
    CONSTRAINT chk_locations_lat CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT chk_locations_lng CHECK (longitude BETWEEN -180 AND 180)
) ENGINE=InnoDB COMMENT='Reusable map locations used by reports, routes, roads and emergency services.';

CREATE TABLE roads (
    road_id                    BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    road_code                  VARCHAR(50) NULL,
    road_name                  VARCHAR(200) NOT NULL,
    road_type                  VARCHAR(80) NULL,
    city                       VARCHAR(100) NULL,
    district                   VARCHAR(100) NULL,
    default_speed_limit_kmh    SMALLINT UNSIGNED NULL,
    is_active                  BOOLEAN NOT NULL DEFAULT TRUE,
    created_at                 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (road_id),
    UNIQUE KEY uq_roads_code (road_code),
    KEY ix_roads_name_city (road_name, city),
    CONSTRAINT chk_roads_speed_limit CHECK (default_speed_limit_kmh IS NULL OR default_speed_limit_kmh <= 250)
) ENGINE=InnoDB COMMENT='Master list of roads managed by the platform.';

CREATE TABLE road_segments (
    road_segment_id            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    road_id                    BIGINT UNSIGNED NOT NULL,
    start_location_id          BIGINT UNSIGNED NOT NULL,
    end_location_id            BIGINT UNSIGNED NOT NULL,
    segment_name               VARCHAR(200) NULL,
    distance_km                DECIMAL(10,3) NOT NULL,
    average_travel_time_min    DECIMAL(8,2) NULL,
    speed_limit_kmh            SMALLINT UNSIGNED NULL,
    lane_count                 TINYINT UNSIGNED NULL,
    is_one_way                 BOOLEAN NOT NULL DEFAULT FALSE,
    encoded_polyline           LONGTEXT NULL,
    is_active                  BOOLEAN NOT NULL DEFAULT TRUE,
    created_at                 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (road_segment_id),
    KEY ix_road_segments_road (road_id),
    KEY ix_road_segments_start (start_location_id),
    KEY ix_road_segments_end (end_location_id),
    CONSTRAINT fk_road_segments_road
        FOREIGN KEY (road_id) REFERENCES roads(road_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_road_segments_start_location
        FOREIGN KEY (start_location_id) REFERENCES locations(location_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_road_segments_end_location
        FOREIGN KEY (end_location_id) REFERENCES locations(location_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_road_segments_distance CHECK (distance_km >= 0),
    CONSTRAINT chk_road_segments_speed CHECK (speed_limit_kmh IS NULL OR speed_limit_kmh <= 250),
    CONSTRAINT chk_road_segments_lanes CHECK (lane_count IS NULL OR lane_count > 0)
) ENGINE=InnoDB COMMENT='Smaller road sections used for risk scoring and route calculation.';

CREATE TABLE user_location_history (
    user_location_id       BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id                BIGINT UNSIGNED NOT NULL,
    latitude               DECIMAL(10,7) NOT NULL,
    longitude              DECIMAL(10,7) NOT NULL,
    accuracy_meters        DECIMAL(10,2) NULL,
    purpose                ENUM('ROUTE_REQUEST','ACCIDENT_REPORT','HAZARD_REPORT','EMERGENCY','OTHER') NOT NULL DEFAULT 'OTHER',
    captured_at            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_location_id),
    KEY ix_user_location_history_user_time (user_id, captured_at),
    CONSTRAINT fk_user_location_history_user
        FOREIGN KEY (user_id) REFERENCES users(user_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT chk_user_location_history_lat CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT chk_user_location_history_lng CHECK (longitude BETWEEN -180 AND 180),
    CONSTRAINT chk_user_location_history_accuracy CHECK (accuracy_meters IS NULL OR accuracy_meters >= 0)
) ENGINE=InnoDB COMMENT='Optional, consent-based location captures for user actions; not continuous tracking.';

CREATE TABLE saved_places (
    saved_place_id         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id                BIGINT UNSIGNED NOT NULL,
    location_id            BIGINT UNSIGNED NOT NULL,
    place_name             VARCHAR(120) NOT NULL,
    place_type             ENUM('HOME','OFFICE','UNIVERSITY','FAVORITE','OTHER') NOT NULL DEFAULT 'OTHER',
    created_at             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (saved_place_id),
    UNIQUE KEY uq_saved_places_user_name (user_id, place_name),
    KEY ix_saved_places_location (location_id),
    CONSTRAINT fk_saved_places_user
        FOREIGN KEY (user_id) REFERENCES users(user_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_saved_places_location
        FOREIGN KEY (location_id) REFERENCES locations(location_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB COMMENT='Named locations saved by users, such as Home or University.';

-- ============================================================================
-- 3. REPORT LOOKUPS: STATUS, ACCIDENT TYPES, SEVERITY, HAZARD TYPES
-- ============================================================================

CREATE TABLE report_statuses (
    status_id              SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    status_code            VARCHAR(40) NOT NULL,
    status_name            VARCHAR(80) NOT NULL,
    description            VARCHAR(255) NULL,
    is_closed_status       BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (status_id),
    UNIQUE KEY uq_report_statuses_code (status_code),
    UNIQUE KEY uq_report_statuses_name (status_name)
) ENGINE=InnoDB COMMENT='Lifecycle states for accident and hazard reports.';

CREATE TABLE accident_types (
    accident_type_id       SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    type_name              VARCHAR(100) NOT NULL,
    description            VARCHAR(255) NULL,
    default_risk_weight    DECIMAL(5,2) NOT NULL DEFAULT 1.00,
    is_active              BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (accident_type_id),
    UNIQUE KEY uq_accident_types_name (type_name),
    CONSTRAINT chk_accident_types_weight CHECK (default_risk_weight >= 0)
) ENGINE=InnoDB COMMENT='Types of road accidents.';

CREATE TABLE accident_severities (
    severity_id            TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    severity_name          VARCHAR(50) NOT NULL,
    risk_weight            DECIMAL(5,2) NOT NULL,
    description            VARCHAR(255) NULL,
    PRIMARY KEY (severity_id),
    UNIQUE KEY uq_accident_severities_name (severity_name),
    CONSTRAINT chk_accident_severities_weight CHECK (risk_weight >= 0)
) ENGINE=InnoDB COMMENT='Severity levels used to weight accident risk.';

CREATE TABLE hazard_types (
    hazard_type_id         SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    hazard_name            VARCHAR(100) NOT NULL,
    description            VARCHAR(255) NULL,
    default_risk_weight    DECIMAL(5,2) NOT NULL DEFAULT 1.00,
    is_active              BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (hazard_type_id),
    UNIQUE KEY uq_hazard_types_name (hazard_name),
    CONSTRAINT chk_hazard_types_weight CHECK (default_risk_weight >= 0)
) ENGINE=InnoDB COMMENT='Road hazard categories such as pothole, waterlogging or broken signal.';

-- ============================================================================
-- 4. UNIFIED COMMUNITY REPORTING MODEL
--    A generic reports parent table is used so images, votes, comments and
--    verification history can have real foreign keys instead of a weak
--    ReportType + ReportId polymorphic reference.
-- ============================================================================

CREATE TABLE reports (
    report_id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    report_type            ENUM('ACCIDENT','HAZARD') NOT NULL,
    user_id                BIGINT UNSIGNED NULL,
    location_id            BIGINT UNSIGNED NOT NULL,
    road_segment_id        BIGINT UNSIGNED NULL,
    status_id              SMALLINT UNSIGNED NOT NULL,
    title                  VARCHAR(200) NOT NULL,
    description            TEXT NULL,
    is_public              BOOLEAN NOT NULL DEFAULT TRUE,
    reported_at            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    resolved_at            DATETIME NULL,
    PRIMARY KEY (report_id),
    KEY ix_reports_user (user_id),
    KEY ix_reports_location (location_id),
    KEY ix_reports_segment (road_segment_id),
    KEY ix_reports_status_type (status_id, report_type),
    KEY ix_reports_reported_at (reported_at),
    CONSTRAINT fk_reports_user
        FOREIGN KEY (user_id) REFERENCES users(user_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_reports_location
        FOREIGN KEY (location_id) REFERENCES locations(location_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_reports_segment
        FOREIGN KEY (road_segment_id) REFERENCES road_segments(road_segment_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_reports_status
        FOREIGN KEY (status_id) REFERENCES report_statuses(status_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB COMMENT='Parent table for all user-submitted accident and hazard reports.';

CREATE TABLE accident_reports (
    report_id              BIGINT UNSIGNED NOT NULL,
    accident_type_id       SMALLINT UNSIGNED NOT NULL,
    severity_id            TINYINT UNSIGNED NOT NULL,
    accident_occurred_at   DATETIME NULL,
    number_of_vehicles     SMALLINT UNSIGNED NULL,
    number_of_injured      SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    number_of_deaths       SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    weather_notes          VARCHAR(255) NULL,
    PRIMARY KEY (report_id),
    KEY ix_accident_reports_type (accident_type_id),
    KEY ix_accident_reports_severity (severity_id),
    CONSTRAINT fk_accident_reports_report
        FOREIGN KEY (report_id) REFERENCES reports(report_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_accident_reports_type
        FOREIGN KEY (accident_type_id) REFERENCES accident_types(accident_type_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_accident_reports_severity
        FOREIGN KEY (severity_id) REFERENCES accident_severities(severity_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB COMMENT='Accident-specific fields for reports whose report_type is ACCIDENT.';

CREATE TABLE hazard_reports (
    report_id              BIGINT UNSIGNED NOT NULL,
    hazard_type_id         SMALLINT UNSIGNED NOT NULL,
    risk_level             ENUM('LOW','MODERATE','HIGH','CRITICAL') NOT NULL DEFAULT 'MODERATE',
    observed_at            DATETIME NULL,
    expected_clearance_at  DATETIME NULL,
    PRIMARY KEY (report_id),
    KEY ix_hazard_reports_type (hazard_type_id),
    KEY ix_hazard_reports_risk (risk_level),
    CONSTRAINT fk_hazard_reports_report
        FOREIGN KEY (report_id) REFERENCES reports(report_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_hazard_reports_type
        FOREIGN KEY (hazard_type_id) REFERENCES hazard_types(hazard_type_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB COMMENT='Hazard-specific fields for reports whose report_type is HAZARD.';

CREATE TABLE report_images (
    image_id               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    report_id              BIGINT UNSIGNED NOT NULL,
    image_url              VARCHAR(1000) NOT NULL,
    caption                VARCHAR(255) NULL,
    uploaded_at            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (image_id),
    KEY ix_report_images_report (report_id),
    CONSTRAINT fk_report_images_report
        FOREIGN KEY (report_id) REFERENCES reports(report_id)
        ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB COMMENT='Images attached to any accident or hazard report.';

CREATE TABLE report_votes (
    vote_id                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    report_id              BIGINT UNSIGNED NOT NULL,
    user_id                BIGINT UNSIGNED NOT NULL,
    vote_type              ENUM('CONFIRM','DISPUTE') NOT NULL,
    created_at             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (vote_id),
    UNIQUE KEY uq_report_votes_report_user (report_id, user_id),
    KEY ix_report_votes_user (user_id),
    CONSTRAINT fk_report_votes_report
        FOREIGN KEY (report_id) REFERENCES reports(report_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_report_votes_user
        FOREIGN KEY (user_id) REFERENCES users(user_id)
        ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB COMMENT='Community confirmation or dispute votes for reports.';

CREATE TABLE report_comments (
    comment_id             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    report_id              BIGINT UNSIGNED NOT NULL,
    user_id                BIGINT UNSIGNED NULL,
    parent_comment_id      BIGINT UNSIGNED NULL,
    comment_text           TEXT NOT NULL,
    is_deleted             BOOLEAN NOT NULL DEFAULT FALSE,
    created_at             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (comment_id),
    KEY ix_report_comments_report (report_id, created_at),
    KEY ix_report_comments_user (user_id),
    KEY ix_report_comments_parent (parent_comment_id),
    CONSTRAINT fk_report_comments_report
        FOREIGN KEY (report_id) REFERENCES reports(report_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_report_comments_user
        FOREIGN KEY (user_id) REFERENCES users(user_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_report_comments_parent
        FOREIGN KEY (parent_comment_id) REFERENCES report_comments(comment_id)
        ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB COMMENT='Discussion and clarification comments on reports.';

CREATE TABLE report_verifications (
    verification_id        BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    report_id              BIGINT UNSIGNED NOT NULL,
    admin_user_id          BIGINT UNSIGNED NULL,
    status_id              SMALLINT UNSIGNED NOT NULL,
    admin_comment          TEXT NULL,
    verified_at            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (verification_id),
    KEY ix_report_verifications_report_time (report_id, verified_at),
    KEY ix_report_verifications_admin (admin_user_id),
    KEY ix_report_verifications_status (status_id),
    CONSTRAINT fk_report_verifications_report
        FOREIGN KEY (report_id) REFERENCES reports(report_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_report_verifications_admin
        FOREIGN KEY (admin_user_id) REFERENCES users(user_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_report_verifications_status
        FOREIGN KEY (status_id) REFERENCES report_statuses(status_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB COMMENT='Audit history of moderator/admin decisions on reports.';

-- ============================================================================
-- 5. VERIFIED / HISTORICAL ACCIDENT DATA
-- ============================================================================

CREATE TABLE accidents (
    accident_id            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_report_id       BIGINT UNSIGNED NULL,
    location_id            BIGINT UNSIGNED NOT NULL,
    road_segment_id        BIGINT UNSIGNED NULL,
    accident_type_id       SMALLINT UNSIGNED NOT NULL,
    severity_id            TINYINT UNSIGNED NOT NULL,
    accident_occurred_at   DATETIME NOT NULL,
    number_of_vehicles     SMALLINT UNSIGNED NULL,
    number_of_injured      SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    number_of_deaths       SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    weather_condition      VARCHAR(100) NULL,
    description            TEXT NULL,
    verified_by            BIGINT UNSIGNED NULL,
    verified_at            DATETIME NULL,
    created_at             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (accident_id),
    UNIQUE KEY uq_accidents_source_report (source_report_id),
    KEY ix_accidents_location_time (location_id, accident_occurred_at),
    KEY ix_accidents_segment_time (road_segment_id, accident_occurred_at),
    KEY ix_accidents_type (accident_type_id),
    KEY ix_accidents_severity (severity_id),
    CONSTRAINT fk_accidents_source_report
        FOREIGN KEY (source_report_id) REFERENCES reports(report_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_accidents_location
        FOREIGN KEY (location_id) REFERENCES locations(location_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_accidents_segment
        FOREIGN KEY (road_segment_id) REFERENCES road_segments(road_segment_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_accidents_type
        FOREIGN KEY (accident_type_id) REFERENCES accident_types(accident_type_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_accidents_severity
        FOREIGN KEY (severity_id) REFERENCES accident_severities(severity_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_accidents_verified_by
        FOREIGN KEY (verified_by) REFERENCES users(user_id)
        ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB COMMENT='Verified accident history used for hotspot and road-risk calculations.';

-- ============================================================================
-- 6. ROAD CONDITION, TRAFFIC & WEATHER OBSERVATIONS
-- ============================================================================

CREATE TABLE road_conditions (
    road_condition_id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    road_segment_id            BIGINT UNSIGNED NOT NULL,
    surface_condition          ENUM('EXCELLENT','GOOD','MODERATE','POOR','DANGEROUS') NOT NULL,
    surface_score              DECIMAL(5,2) NOT NULL,
    lighting_score             DECIMAL(5,2) NULL,
    drainage_score             DECIMAL(5,2) NULL,
    visibility_score           DECIMAL(5,2) NULL,
    overall_condition_score    DECIMAL(5,2) NOT NULL,
    description                TEXT NULL,
    source_type                ENUM('ADMIN','USER_REPORT','API','SURVEY','OTHER') NOT NULL DEFAULT 'ADMIN',
    recorded_by                BIGINT UNSIGNED NULL,
    recorded_at                DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (road_condition_id),
    KEY ix_road_conditions_segment_time (road_segment_id, recorded_at),
    KEY ix_road_conditions_recorded_by (recorded_by),
    CONSTRAINT fk_road_conditions_segment
        FOREIGN KEY (road_segment_id) REFERENCES road_segments(road_segment_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_road_conditions_recorded_by
        FOREIGN KEY (recorded_by) REFERENCES users(user_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT chk_road_conditions_surface_score CHECK (surface_score BETWEEN 0 AND 100),
    CONSTRAINT chk_road_conditions_lighting_score CHECK (lighting_score IS NULL OR lighting_score BETWEEN 0 AND 100),
    CONSTRAINT chk_road_conditions_drainage_score CHECK (drainage_score IS NULL OR drainage_score BETWEEN 0 AND 100),
    CONSTRAINT chk_road_conditions_visibility_score CHECK (visibility_score IS NULL OR visibility_score BETWEEN 0 AND 100),
    CONSTRAINT chk_road_conditions_overall_score CHECK (overall_condition_score BETWEEN 0 AND 100)
) ENGINE=InnoDB COMMENT='Historical road quality observations for each segment.';

CREATE TABLE traffic_conditions (
    traffic_condition_id       BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    road_segment_id            BIGINT UNSIGNED NOT NULL,
    traffic_level              ENUM('LOW','MODERATE','HEAVY','SEVERE') NOT NULL,
    average_speed_kmh          DECIMAL(6,2) NULL,
    congestion_score           DECIMAL(5,2) NOT NULL,
    source                     VARCHAR(100) NULL,
    recorded_at                DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (traffic_condition_id),
    KEY ix_traffic_conditions_segment_time (road_segment_id, recorded_at),
    CONSTRAINT fk_traffic_conditions_segment
        FOREIGN KEY (road_segment_id) REFERENCES road_segments(road_segment_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT chk_traffic_conditions_speed CHECK (average_speed_kmh IS NULL OR average_speed_kmh >= 0),
    CONSTRAINT chk_traffic_conditions_score CHECK (congestion_score BETWEEN 0 AND 100)
) ENGINE=InnoDB COMMENT='Traffic snapshots used by fastest and safest route calculations.';

CREATE TABLE weather_conditions (
    weather_condition_id       BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    road_segment_id            BIGINT UNSIGNED NOT NULL,
    weather_type               VARCHAR(80) NOT NULL,
    temperature_c              DECIMAL(5,2) NULL,
    rainfall_mm                DECIMAL(8,2) NULL,
    visibility_meters          DECIMAL(10,2) NULL,
    weather_risk_score         DECIMAL(5,2) NOT NULL,
    source                     VARCHAR(100) NULL,
    recorded_at                DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (weather_condition_id),
    KEY ix_weather_conditions_segment_time (road_segment_id, recorded_at),
    CONSTRAINT fk_weather_conditions_segment
        FOREIGN KEY (road_segment_id) REFERENCES road_segments(road_segment_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT chk_weather_conditions_rainfall CHECK (rainfall_mm IS NULL OR rainfall_mm >= 0),
    CONSTRAINT chk_weather_conditions_visibility CHECK (visibility_meters IS NULL OR visibility_meters >= 0),
    CONSTRAINT chk_weather_conditions_risk CHECK (weather_risk_score BETWEEN 0 AND 100)
) ENGINE=InnoDB COMMENT='Weather snapshots for weather-aware safety scoring.';

-- ============================================================================
-- 7. ROAD SAFETY SCORE ENGINE
-- ============================================================================

CREATE TABLE safety_scores (
    safety_score_id            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    road_segment_id            BIGINT UNSIGNED NOT NULL,
    overall_safety_score       DECIMAL(5,2) NOT NULL,
    risk_level                 ENUM('LOW','MODERATE','HIGH','CRITICAL') NOT NULL,
    methodology_version        VARCHAR(30) NOT NULL DEFAULT '1.0',
    calculated_at              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    valid_until                DATETIME NULL,
    PRIMARY KEY (safety_score_id),
    KEY ix_safety_scores_segment_time (road_segment_id, calculated_at),
    KEY ix_safety_scores_risk (risk_level),
    CONSTRAINT fk_safety_scores_segment
        FOREIGN KEY (road_segment_id) REFERENCES road_segments(road_segment_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT chk_safety_scores_overall CHECK (overall_safety_score BETWEEN 0 AND 100)
) ENGINE=InnoDB COMMENT='Calculated safety score snapshots for road segments. Higher score means safer.';

CREATE TABLE safety_score_factors (
    factor_id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    safety_score_id            BIGINT UNSIGNED NOT NULL,
    factor_type                ENUM('ACCIDENT','HAZARD','ROAD_CONDITION','TRAFFIC','WEATHER','LIGHTING','OTHER') NOT NULL,
    raw_value                  DECIMAL(12,4) NULL,
    normalized_risk_score      DECIMAL(5,2) NOT NULL,
    factor_weight              DECIMAL(6,5) NOT NULL,
    weighted_risk_score        DECIMAL(7,3) NOT NULL,
    details                    VARCHAR(500) NULL,
    PRIMARY KEY (factor_id),
    UNIQUE KEY uq_safety_score_factor_type (safety_score_id, factor_type),
    CONSTRAINT fk_safety_score_factors_score
        FOREIGN KEY (safety_score_id) REFERENCES safety_scores(safety_score_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT chk_safety_factor_normalized CHECK (normalized_risk_score BETWEEN 0 AND 100),
    CONSTRAINT chk_safety_factor_weight CHECK (factor_weight BETWEEN 0 AND 1),
    CONSTRAINT chk_safety_factor_weighted CHECK (weighted_risk_score >= 0)
) ENGINE=InnoDB COMMENT='Explainable factor-by-factor breakdown behind each road safety score.';

-- ============================================================================
-- 8. ROUTE GENERATION & SAVED ROUTES
-- ============================================================================

CREATE TABLE routes (
    route_id                   BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id                    BIGINT UNSIGNED NULL,
    start_location_id          BIGINT UNSIGNED NOT NULL,
    destination_location_id    BIGINT UNSIGNED NOT NULL,
    route_type                 ENUM('SAFEST','FASTEST','SHORTEST') NOT NULL,
    total_distance_km          DECIMAL(10,3) NOT NULL,
    estimated_duration_min     DECIMAL(10,2) NULL,
    overall_safety_score       DECIMAL(5,2) NULL,
    encoded_polyline           LONGTEXT NULL,
    generated_at               DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at                 DATETIME NULL,
    PRIMARY KEY (route_id),
    KEY ix_routes_user_time (user_id, generated_at),
    KEY ix_routes_start_destination (start_location_id, destination_location_id),
    KEY ix_routes_type (route_type),
    CONSTRAINT fk_routes_user
        FOREIGN KEY (user_id) REFERENCES users(user_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_routes_start_location
        FOREIGN KEY (start_location_id) REFERENCES locations(location_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_routes_destination_location
        FOREIGN KEY (destination_location_id) REFERENCES locations(location_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_routes_distance CHECK (total_distance_km >= 0),
    CONSTRAINT chk_routes_duration CHECK (estimated_duration_min IS NULL OR estimated_duration_min >= 0),
    CONSTRAINT chk_routes_safety_score CHECK (overall_safety_score IS NULL OR overall_safety_score BETWEEN 0 AND 100)
) ENGINE=InnoDB COMMENT='Generated route alternatives such as safest, fastest and shortest.';

CREATE TABLE route_segments (
    route_segment_id           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    route_id                   BIGINT UNSIGNED NOT NULL,
    road_segment_id            BIGINT UNSIGNED NOT NULL,
    sequence_no                INT UNSIGNED NOT NULL,
    distance_km                DECIMAL(10,3) NOT NULL,
    estimated_duration_min     DECIMAL(10,2) NULL,
    segment_safety_score       DECIMAL(5,2) NULL,
    PRIMARY KEY (route_segment_id),
    UNIQUE KEY uq_route_segments_sequence (route_id, sequence_no),
    KEY ix_route_segments_road_segment (road_segment_id),
    CONSTRAINT fk_route_segments_route
        FOREIGN KEY (route_id) REFERENCES routes(route_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_route_segments_road_segment
        FOREIGN KEY (road_segment_id) REFERENCES road_segments(road_segment_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_route_segments_sequence CHECK (sequence_no > 0),
    CONSTRAINT chk_route_segments_distance CHECK (distance_km >= 0),
    CONSTRAINT chk_route_segments_duration CHECK (estimated_duration_min IS NULL OR estimated_duration_min >= 0),
    CONSTRAINT chk_route_segments_safety CHECK (segment_safety_score IS NULL OR segment_safety_score BETWEEN 0 AND 100)
) ENGINE=InnoDB COMMENT='Many-to-many bridge between routes and road segments, preserving segment order.';

CREATE TABLE saved_routes (
    saved_route_id             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id                    BIGINT UNSIGNED NOT NULL,
    route_id                   BIGINT UNSIGNED NOT NULL,
    custom_name                VARCHAR(150) NOT NULL,
    created_at                 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (saved_route_id),
    UNIQUE KEY uq_saved_routes_user_name (user_id, custom_name),
    UNIQUE KEY uq_saved_routes_user_route (user_id, route_id),
    KEY ix_saved_routes_route (route_id),
    CONSTRAINT fk_saved_routes_user
        FOREIGN KEY (user_id) REFERENCES users(user_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_saved_routes_route
        FOREIGN KEY (route_id) REFERENCES routes(route_id)
        ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB COMMENT='Routes explicitly bookmarked by users.';

-- ============================================================================
-- 9. EMERGENCY SERVICES
-- ============================================================================

CREATE TABLE emergency_service_types (
    service_type_id            SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    service_type_name          VARCHAR(80) NOT NULL,
    description                VARCHAR(255) NULL,
    PRIMARY KEY (service_type_id),
    UNIQUE KEY uq_emergency_service_types_name (service_type_name)
) ENGINE=InnoDB COMMENT='Hospital, Police Station, Fire Service, Ambulance and similar types.';

CREATE TABLE emergency_services (
    emergency_service_id       BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    service_type_id            SMALLINT UNSIGNED NOT NULL,
    location_id                BIGINT UNSIGNED NOT NULL,
    service_name               VARCHAR(200) NOT NULL,
    phone                      VARCHAR(30) NULL,
    emergency_phone            VARCHAR(30) NULL,
    opening_hours              VARCHAR(255) NULL,
    is_24_hours                BOOLEAN NOT NULL DEFAULT FALSE,
    website_url                VARCHAR(1000) NULL,
    is_verified                BOOLEAN NOT NULL DEFAULT FALSE,
    is_active                  BOOLEAN NOT NULL DEFAULT TRUE,
    created_at                 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (emergency_service_id),
    KEY ix_emergency_services_type (service_type_id),
    KEY ix_emergency_services_location (location_id),
    KEY ix_emergency_services_name (service_name),
    CONSTRAINT fk_emergency_services_type
        FOREIGN KEY (service_type_id) REFERENCES emergency_service_types(service_type_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_emergency_services_location
        FOREIGN KEY (location_id) REFERENCES locations(location_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB COMMENT='Emergency facilities displayed near a user, route or accident location.';

-- ============================================================================
-- 10. NOTIFICATIONS & SAFETY ALERTS
-- ============================================================================

CREATE TABLE notification_types (
    notification_type_id       SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    type_code                  VARCHAR(50) NOT NULL,
    type_name                  VARCHAR(100) NOT NULL,
    description                VARCHAR(255) NULL,
    PRIMARY KEY (notification_type_id),
    UNIQUE KEY uq_notification_types_code (type_code),
    UNIQUE KEY uq_notification_types_name (type_name)
) ENGINE=InnoDB COMMENT='Categories of notifications sent by the platform.';

CREATE TABLE notifications (
    notification_id            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id                    BIGINT UNSIGNED NOT NULL,
    notification_type_id       SMALLINT UNSIGNED NOT NULL,
    report_id                  BIGINT UNSIGNED NULL,
    route_id                   BIGINT UNSIGNED NULL,
    road_segment_id            BIGINT UNSIGNED NULL,
    title                      VARCHAR(200) NOT NULL,
    message                    TEXT NOT NULL,
    is_read                    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at                 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at                    DATETIME NULL,
    PRIMARY KEY (notification_id),
    KEY ix_notifications_user_read_time (user_id, is_read, created_at),
    KEY ix_notifications_type (notification_type_id),
    KEY ix_notifications_report (report_id),
    KEY ix_notifications_route (route_id),
    KEY ix_notifications_segment (road_segment_id),
    CONSTRAINT fk_notifications_user
        FOREIGN KEY (user_id) REFERENCES users(user_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_notifications_type
        FOREIGN KEY (notification_type_id) REFERENCES notification_types(notification_type_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_notifications_report
        FOREIGN KEY (report_id) REFERENCES reports(report_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_notifications_route
        FOREIGN KEY (route_id) REFERENCES routes(route_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_notifications_segment
        FOREIGN KEY (road_segment_id) REFERENCES road_segments(road_segment_id)
        ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB COMMENT='User-specific safety, report, route and system notifications.';

-- ============================================================================
-- 11. ADMINISTRATION, FEEDBACK & SYSTEM CONFIGURATION
-- ============================================================================

CREATE TABLE admin_actions (
    admin_action_id            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    admin_user_id              BIGINT UNSIGNED NULL,
    action_type                VARCHAR(100) NOT NULL,
    entity_type                VARCHAR(100) NULL,
    entity_id                  BIGINT UNSIGNED NULL,
    description                TEXT NULL,
    metadata_json              JSON NULL,
    action_at                  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (admin_action_id),
    KEY ix_admin_actions_admin_time (admin_user_id, action_at),
    KEY ix_admin_actions_entity (entity_type, entity_id),
    CONSTRAINT fk_admin_actions_admin
        FOREIGN KEY (admin_user_id) REFERENCES users(user_id)
        ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB COMMENT='Audit log for important administrator and moderator actions.';

CREATE TABLE feedback (
    feedback_id                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id                    BIGINT UNSIGNED NULL,
    subject                    VARCHAR(200) NOT NULL,
    message                    TEXT NOT NULL,
    rating                     TINYINT UNSIGNED NULL,
    status                     ENUM('OPEN','IN_REVIEW','RESOLVED','CLOSED') NOT NULL DEFAULT 'OPEN',
    submitted_at               DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at                DATETIME NULL,
    PRIMARY KEY (feedback_id),
    KEY ix_feedback_user (user_id),
    KEY ix_feedback_status_time (status, submitted_at),
    CONSTRAINT fk_feedback_user
        FOREIGN KEY (user_id) REFERENCES users(user_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT chk_feedback_rating CHECK (rating IS NULL OR rating BETWEEN 1 AND 5)
) ENGINE=InnoDB COMMENT='User feedback, suggestions and complaints.';

CREATE TABLE system_settings (
    setting_id                 BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    setting_key                VARCHAR(120) NOT NULL,
    setting_value              TEXT NOT NULL,
    data_type                  ENUM('STRING','INTEGER','DECIMAL','BOOLEAN','JSON') NOT NULL DEFAULT 'STRING',
    description                VARCHAR(500) NULL,
    updated_by                 BIGINT UNSIGNED NULL,
    updated_at                 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (setting_id),
    UNIQUE KEY uq_system_settings_key (setting_key),
    KEY ix_system_settings_updated_by (updated_by),
    CONSTRAINT fk_system_settings_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(user_id)
        ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB COMMENT='Configurable application settings including safety-score weights.';

-- ============================================================================
-- 12. SEED / LOOKUP DATA
-- ============================================================================

INSERT INTO roles (role_name, description) VALUES
('Admin', 'Full platform administration and configuration access.'),
('Moderator', 'Can review and verify accident/hazard reports.'),
('User', 'Standard registered SafePath BD user.');

INSERT INTO report_statuses (status_code, status_name, description, is_closed_status) VALUES
('PENDING', 'Pending', 'Submitted and waiting for review.', FALSE),
('UNDER_REVIEW', 'Under Review', 'Currently being reviewed by a moderator or administrator.', FALSE),
('VERIFIED', 'Verified', 'Report has been verified as valid.', FALSE),
('REJECTED', 'Rejected', 'Report was determined to be invalid or insufficient.', TRUE),
('RESOLVED', 'Resolved', 'The reported issue is no longer active.', TRUE),
('DUPLICATE', 'Duplicate', 'The same issue has already been reported.', TRUE),
('NEEDS_INFO', 'Needs More Information', 'Additional information is required from the reporter.', FALSE);

INSERT INTO accident_severities (severity_name, risk_weight, description) VALUES
('Minor', 1.00, 'No or minor injuries and limited damage.'),
('Moderate', 2.00, 'Noticeable injuries or property damage.'),
('Severe', 4.00, 'Serious injuries and/or major damage.'),
('Fatal', 5.00, 'One or more fatalities involved.');

INSERT INTO accident_types (type_name, description, default_risk_weight) VALUES
('Vehicle Collision', 'Collision involving two or more motor vehicles.', 2.00),
('Pedestrian Accident', 'Accident involving a pedestrian.', 3.00),
('Motorcycle Accident', 'Accident involving a motorcycle.', 2.50),
('Bus Accident', 'Accident involving a bus.', 2.50),
('Truck Accident', 'Accident involving a truck or heavy vehicle.', 2.75),
('Rollover', 'Vehicle rollover accident.', 3.00),
('Hit and Run', 'Collision where a responsible party leaves the scene.', 3.00),
('Other', 'Other road accident type.', 1.50);

INSERT INTO hazard_types (hazard_name, description, default_risk_weight) VALUES
('Pothole', 'Dangerous pothole or damaged road surface.', 2.00),
('Broken Road', 'Severely damaged or broken road section.', 3.00),
('Waterlogging', 'Water accumulation affecting safe travel.', 2.50),
('Broken Traffic Signal', 'Traffic signal not operating correctly.', 3.50),
('Road Construction', 'Construction activity affecting normal road use.', 2.00),
('Illegal Parking', 'Vehicles creating an unsafe obstruction.', 1.50),
('Poor Street Lighting', 'Insufficient lighting increasing night-time risk.', 2.00),
('Fallen Tree', 'Tree or large branch obstructing the road.', 3.00),
('Road Block', 'Road is partially or fully blocked.', 3.00),
('Dangerous Intersection', 'Intersection with elevated accident or conflict risk.', 3.50),
('Debris on Road', 'Objects or debris creating a road hazard.', 2.00),
('Other', 'Other road safety hazard.', 1.50);

INSERT INTO emergency_service_types (service_type_name, description) VALUES
('Hospital', 'Hospital or medical facility.'),
('Police Station', 'Police station or police assistance point.'),
('Fire Service', 'Fire and rescue service station.'),
('Ambulance', 'Ambulance or emergency medical transport provider.'),
('Emergency Center', 'Other emergency assistance center.');

INSERT INTO notification_types (type_code, type_name, description) VALUES
('HAZARD_ALERT', 'Hazard Alert', 'Nearby or route-related hazard warning.'),
('ACCIDENT_ALERT', 'Accident Alert', 'Nearby or route-related accident warning.'),
('EMERGENCY_ALERT', 'Emergency Alert', 'Urgent road safety or emergency notification.'),
('REPORT_VERIFIED', 'Report Verified', 'User report has been verified.'),
('REPORT_REJECTED', 'Report Rejected', 'User report has been rejected.'),
('REPORT_RESOLVED', 'Report Resolved', 'Reported issue has been resolved.'),
('ROAD_RISK_ALERT', 'Road Risk Alert', 'Road segment safety level has become risky.'),
('SYSTEM', 'System Notification', 'General platform notification.');

INSERT INTO system_settings (setting_key, setting_value, data_type, description) VALUES
('safety_weight_accident', '0.35', 'DECIMAL', 'Weight of historical accident risk in the safety score.'),
('safety_weight_hazard', '0.25', 'DECIMAL', 'Weight of active hazard risk in the safety score.'),
('safety_weight_road_condition', '0.15', 'DECIMAL', 'Weight of road condition risk in the safety score.'),
('safety_weight_traffic', '0.10', 'DECIMAL', 'Weight of traffic/congestion risk in the safety score.'),
('safety_weight_weather', '0.10', 'DECIMAL', 'Weight of weather risk in the safety score.'),
('safety_weight_lighting', '0.05', 'DECIMAL', 'Weight of lighting risk in the safety score.'),
('safety_score_methodology_version', '1.0', 'STRING', 'Current safety score calculation methodology version.'),
('report_vote_confirmation_threshold', '3', 'INTEGER', 'Suggested number of community confirmations before prioritizing a report for review.'),
('default_route_search_radius_km', '25', 'DECIMAL', 'Default maximum route-search radius where applicable.'),
('safety_score_cache_minutes', '15', 'INTEGER', 'Suggested validity period for cached route safety calculations.');

-- ============================================================================
-- 13. DATA-INTEGRITY TRIGGERS FOR REPORT SUBTYPES
-- ============================================================================

DELIMITER $$

CREATE TRIGGER trg_accident_reports_validate_type_insert
BEFORE INSERT ON accident_reports
FOR EACH ROW
BEGIN
    DECLARE v_report_type VARCHAR(20);
    SELECT report_type INTO v_report_type
    FROM reports
    WHERE report_id = NEW.report_id;

    IF v_report_type IS NULL OR v_report_type <> 'ACCIDENT' THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'accident_reports requires a parent reports row with report_type = ACCIDENT';
    END IF;
END$$

CREATE TRIGGER trg_hazard_reports_validate_type_insert
BEFORE INSERT ON hazard_reports
FOR EACH ROW
BEGIN
    DECLARE v_report_type VARCHAR(20);
    SELECT report_type INTO v_report_type
    FROM reports
    WHERE report_id = NEW.report_id;

    IF v_report_type IS NULL OR v_report_type <> 'HAZARD' THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'hazard_reports requires a parent reports row with report_type = HAZARD';
    END IF;
END$$

CREATE TRIGGER trg_reports_prevent_type_change
BEFORE UPDATE ON reports
FOR EACH ROW
BEGIN
    IF NEW.report_type <> OLD.report_type THEN
        IF EXISTS (SELECT 1 FROM accident_reports WHERE report_id = OLD.report_id)
           OR EXISTS (SELECT 1 FROM hazard_reports WHERE report_id = OLD.report_id) THEN
            SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Cannot change report_type after a subtype record has been created';
        END IF;
    END IF;
END$$

CREATE TRIGGER trg_accidents_validate_source_report_insert
BEFORE INSERT ON accidents
FOR EACH ROW
BEGIN
    DECLARE v_report_type VARCHAR(20);

    IF NEW.source_report_id IS NOT NULL THEN
        SELECT report_type INTO v_report_type
        FROM reports
        WHERE report_id = NEW.source_report_id;

        IF v_report_type IS NULL OR v_report_type <> 'ACCIDENT' THEN
            SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'accidents.source_report_id must reference an ACCIDENT report';
        END IF;
    END IF;
END$$

DELIMITER ;

-- ============================================================================
-- 14. USEFUL VIEWS
-- ============================================================================

CREATE VIEW vw_report_overview AS
SELECT
    r.report_id,
    r.report_type,
    r.title,
    r.description,
    rs.status_code,
    rs.status_name,
    r.user_id,
    u.full_name AS reporter_name,
    r.location_id,
    l.latitude,
    l.longitude,
    l.landmark_name,
    l.area_name,
    r.road_segment_id,
    r.reported_at,
    r.resolved_at,
    (SELECT COUNT(*) FROM report_votes rv WHERE rv.report_id = r.report_id AND rv.vote_type = 'CONFIRM') AS confirm_votes,
    (SELECT COUNT(*) FROM report_votes rv WHERE rv.report_id = r.report_id AND rv.vote_type = 'DISPUTE') AS dispute_votes
FROM reports r
JOIN report_statuses rs ON rs.status_id = r.status_id
JOIN locations l ON l.location_id = r.location_id
LEFT JOIN users u ON u.user_id = r.user_id;

CREATE VIEW vw_latest_segment_safety_score AS
SELECT ss.*
FROM safety_scores ss
JOIN (
    SELECT road_segment_id, MAX(calculated_at) AS max_calculated_at
    FROM safety_scores
    GROUP BY road_segment_id
) latest
    ON latest.road_segment_id = ss.road_segment_id
   AND latest.max_calculated_at = ss.calculated_at;

CREATE VIEW vw_emergency_services_with_location AS
SELECT
    es.emergency_service_id,
    est.service_type_name,
    es.service_name,
    es.phone,
    es.emergency_phone,
    es.opening_hours,
    es.is_24_hours,
    es.website_url,
    es.is_verified,
    es.is_active,
    l.latitude,
    l.longitude,
    l.address_line,
    l.landmark_name,
    l.area_name,
    l.city,
    l.district
FROM emergency_services es
JOIN emergency_service_types est ON est.service_type_id = es.service_type_id
JOIN locations l ON l.location_id = es.location_id;

-- ============================================================================
-- 15. FINAL SANITY CHECK
-- ============================================================================

SELECT 'SafePath BD database created successfully.' AS result;
SELECT DATABASE() AS active_database;

-- End of file.
