using Microsoft.Extensions.Options;
using SafePathBD.Web.Common;
using SafePathBD.Web.Models.DTOs.IntelligentRouting;
using SafePathBD.Web.Services.IntelligentRouting;
using SafePathBD.Web.Services.Interfaces;

namespace SafePathBD.Web.Services.Implementations;

/// <summary>
/// Deterministic Yen-inspired K-best planner. The primary time-dependent path is found first;
/// additional candidates are generated by bounded edge suppression plus useful single-mode
/// searches. This avoids an unbounded combinatorial search while keeping alternatives distinct.
/// </summary>
public sealed class KBestJourneyPlanner : IKBestJourneyPlanner
{
    private readonly ITimeDependentJourneyRouter _router;
    private readonly IntelligentMobilityOptions _options;

    public KBestJourneyPlanner(
        ITimeDependentJourneyRouter router,
        IOptions<IntelligentMobilityOptions> options)
    {
        _router = router;
        _options = options.Value;
    }

    public async Task<IReadOnlyList<JourneyPath>> FindCandidatesAsync(
        MobilityGraph graph,
        IntelligentRouteRequest request,
        IReadOnlySet<int>? globallyBlockedEdgeIds = null,
        CancellationToken cancellationToken = default)
    {
        var results = new List<JourneyPath>();
        var seen = new HashSet<string>(StringComparer.Ordinal);

        async Task AddAsync(IReadOnlySet<int>? excluded = null, string? singleMode = null)
        {
            if (results.Count >= _options.CandidatePoolSize) return;
            var merged = Merge(globallyBlockedEdgeIds, excluded);
            var path = await _router.FindBestAsync(graph, request, merged, singleMode, cancellationToken);
            if (path is null) return;
            var signature = Signature(path);
            if (seen.Add(signature)) results.Add(path);
        }

        await AddAsync();
        if (results.Count == 0)
        {
            return results;
        }

        foreach (var mode in request.EnabledModes
                     .Select(m => m.Trim().ToUpperInvariant())
                     .Where(m => m is MobilityModes.Car or MobilityModes.Motorbike or MobilityModes.Rickshaw or MobilityModes.Walk))
        {
            await AddAsync(singleMode: mode);
        }

        var seedPaths = results.Take(3).ToArray();
        foreach (var path in seedPaths)
        {
            var physicalEdges = path.Steps.Where(s => s.Edge is not null).Select(s => s.Edge!.Id).Distinct().ToArray();
            foreach (var edgeId in physicalEdges.Take(10))
            {
                await AddAsync(new HashSet<int> { edgeId });
                if (results.Count >= _options.CandidatePoolSize) break;
            }
            if (results.Count >= _options.CandidatePoolSize) break;
        }

        return results
            .OrderBy(p => p.GeneralizedSearchCost)
            .Take(_options.CandidatePoolSize)
            .ToArray();
    }

    private static IReadOnlySet<int>? Merge(IReadOnlySet<int>? first, IReadOnlySet<int>? second)
    {
        if ((first is null || first.Count == 0) && (second is null || second.Count == 0)) return null;
        var result = new HashSet<int>();
        if (first is not null) result.UnionWith(first);
        if (second is not null) result.UnionWith(second);
        return result;
    }

    private static string Signature(JourneyPath path) => string.Join(
        '|',
        path.Steps.Select(step => step.Edge is null
            ? $"T:{step.Mode}:{step.TransferNote}"
            : $"E:{step.Edge.Id}:{step.Mode}"));
}
